# Rehan Khan || 221A059 || 21

In [ ]:
# Rehan Khan || 21
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Ads_Optimisation.csv')
dataset.head()

   Ad 1  Ad 2  Ad 3  Ad 4  Ad 5  Ad 6  Ad 7  Ad 8  Ad 9  Ad 10
0     1     0     0     0     1     0     0     0     1      0
1     0     0     0     0     0     0     0     0     1      0
2     0     0     0     0     0     0     0     0     0      0
3     0     1     0     0     0     0     0     1     0      0
4     0     0     0     0     0     0     0     0     0      0

In [ ]:
# Rehan Khan || 21
import random
N = 10000
d = 10
ads_selected_random = []
total_reward_random = 0
for n in range(0, N):
    ad = random.randrange(d)  # random add selection
    ads_selected_random.append(ad)
    reward = dataset.values[n, ad]
    total_reward_random = total_reward_random + reward

In [ ]:
# Rehan Khan || 21
print(total_reward_random)

1242

## Now using Upper Confidence Bound Algorithm

In [ ]:
import math
import pandas as pd

# Implementing UCB
N = 10000
d = 10
ads_selected = []
numbers_of_selections = [0] * d
sums_of_reward = [0] * d
total_reward = 0

for n in range(0, N):
    ad = 0
    max_upper_bound = 0
    for i in range(0, d):
        if (numbers_of_selections[i] > 0):
            average_reward = sums_of_reward[i] / numbers_of_selections[i]
            # Calculating the confidence interval (delta)
            delta_i = math.sqrt(3/2 * math.log(n + 1) / numbers_of_selections[i])
            upper_bound = average_reward + delta_i
        else:
            # High value to ensure every ad is selected at least once at the start
            upper_bound = 1e400

        if upper_bound > max_upper_bound:
            max_upper_bound = upper_bound
            ad = i

    # --- Updating variables ---
    ads_selected.append(ad)
    numbers_of_selections[ad] += 1
    reward = dataset.values[n, ad]
    sums_of_reward[ad] += reward
    total_reward += reward

## Display the final results

In [ ]:
print(f"Total Reward (UCB): {total_reward}")

Total Reward (UCB): 2178

## Final Comparison

In [ ]:
print(f"Total Reward (Random Selection): {total_reward_random}")
print(f"Total Reward (UCB): {total_reward}")

Total Reward (Random Selection): 1242
Total Reward (UCB): 2178

In [ ]:
pd.Series(ads_selected_random).tail(1000).value_counts()

1    114
7    112
0    109
9    104
3    103
4    103
5     92
6     91
8     90
2     82
Name: count, dtype: int64